# Generated by Django 4.0.2 on 2022-02-05 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FiksturModelim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ulke_id', models.IntegerField()),
                ('Sezon_id', models.IntegerField()),
                ('idx', models.CharField(max_length=20)),
                ('Nesine_id', models.IntegerField()),
                ('Canlı_Seç', models.IntegerField()),
                ('Seç_id', models.IntegerField()),
                ('ev_id', models.IntegerField()),
                ('dep_id', models.IntegerField()),
                ('Ulke', models.CharField(max_length=20)),
                ('Lig', models.CharField(max_length=20)),
                ('Tarih', models.DateField(blank=True, null=True)),
                ('Sezon_Yıl', models.CharField(max_length=20)),
                ('Saat', models.TextField()),
                ('Lig_Adı', models.CharField(max_length=20)),
                ('Ev', models.CharField(max_length=20)),
                ('Dep', models.CharField(max_length=20)),
                ('Dk_Skor', models.CharField(max_length=20)),
                ('Canlı_skor', models.CharField(max_length=20)),
                ('iye_s', models.IntegerField()),
                ('iyd_s', models.IntegerField()),
                ('mse_s', models.IntegerField()),
                ('msd_s', models.IntegerField()),
                ('OranMS1', models.FloatField()),
                ('OranMS0', models.FloatField()),
                ('OranMS2', models.FloatField()),
                ('OranAlt', models.FloatField()),
                ('OranÜst', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='myfix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evtak', models.CharField(max_length=10)),
                ('deptak', models.CharField(max_length=10)),
                ('ulke', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorial_title', models.CharField(max_length=200)),
                ('tutorial_content', models.TextField()),
                ('tutorial_published', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
