# Generated by Django 4.0.2 on 2022-02-06 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='myfix',
        ),
        migrations.DeleteModel(
            name='Tutorial',
        ),
    ]
