# Generated by Django 3.2.12 on 2022-02-06 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_puandurumu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puandurumu',
            old_name='Attıgı_İ',
            new_name='Attığı_İ',
        ),
        migrations.RenameField(
            model_name='puandurumu',
            old_name='Yedigi_İ',
            new_name='Yediği_İ',
        ),
    ]
