# Generated by Django 3.2.12 on 2022-02-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220206_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='puandurumu',
            name='Ligİd',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
